feat: Announcement scheduler
USSF-ORBIT/ussf-portal-cms pull request #262
Opened 2023-02-08 16:51 UTC by jcbcapps

# SC-1083

## Proposed changes

---

## Reviewer notes

## Setup

---

## Code review steps

### As the original developer, I have

- [ ] Met the acceptance criteria, or will meet them in subsequent PRs or stories
  - ... 
- [ ] Created new stories in Storybook if applicable
  - [ ] Checked that all Storybook accessibility checks are passing
- [ ] Created/modified automated unit tests in Jest
  - [ ] Including jest-axe checks when UI changes
- [ ] Created/modified automated E2E tests in Playwright
  - [ ] Including [axe-playwright](https://github.com/abhinaba-ghosh/axe-playwright) checks when UI changes
  - [ ] Checked that the E2E test build is not failing
- Performed [a11y testing](https://github.com/trussworks/accessibility/blob/master/sample_a11y_testing_process.md):
  - [ ] Checked responsiveness in mobile, tablet, and desktop
  - [ ] Checked keyboard navigability
  - [ ] Tested with [VoiceOver](https://dequeuniversity.com/screenreaders/voiceover-keyboard-shortcuts) in Safari
  - [ ] Checked VO's [rotor menu](https://github.com/trussworks/accessibility/blob/master/README.md#how-to-use-the-rotor-menu) for landmarks, page heading structure and links
  - [ ] Used a browser a11y tool to check for issues (WAVE, axe, ANDI or Accessibility addon tab for Storybook)
- [ ] Requested a design review for user-facing changes
- For any new migrations/schema changes:
  - [ ] Followed guidelines for zero-downtime deploys

### As code reviewer(s), I have

- [ ] Pulled this branch locally and tested it
- [ ] Reviewed this code and left comments
- [ ] Checked that all code is adequately covered by tests
  - [ ] Checked that the E2E test build is not failing
- [ ] Made it clear which comments need to be addressed before this work is merged
- [ ] Considered marking this as accepted even if there are small changes needed
- Performed [a11y testing](https://github.com/trussworks/accessibility/blob/master/sample_a11y_testing_process.md):
  - [ ] Checked responsiveness in mobile, tablet, and desktop
  - [ ] Checked keyboard navigability
  - [ ] Tested with [VoiceOver](https://dequeuniversity.com/screenreaders/voiceover-keyboard-shortcuts) in Safari
  - [ ] Checked VO's [rotor menu](https://github.com/trussworks/accessibility/blob/master/README.md#how-to-use-the-rotor-menu) for landmarks, page heading structure and links
  - [ ] Used a browser a11y tool to check for issues (WAVE, axe, ANDI or Accessibility addon tab for Storybook)

### As a designer reviewer, I have

- [ ] Checked in the design translated visually
- [ ] Checked behavior
- [ ] Checked different states (empty, one, some, error)
- [ ] Checked for landmarks, page heading structure, and links
- [ ] Tried to break the intended flow
- Performed [a11y testing](https://github.com/trussworks/accessibility/blob/master/sample_a11y_testing_process.md):
  - [ ] Checked responsiveness in mobile, tablet, and desktop
  - [ ] Checked keyboard navigability
  - [ ] Tested with [VoiceOver](https://dequeuniversity.com/screenreaders/voiceover-keyboard-shortcuts) in Safari
  - [ ] Checked VO's [rotor menu](https://github.com/trussworks/accessibility/blob/master/README.md#how-to-use-the-rotor-menu) for landmarks, page heading structure and links
  - [ ] Used a browser a11y tool to check for issues (WAVE, axe, ANDI or Accessibility addon tab for Storybook)

---

## Screenshots

2023-02-09 19:12 UTC, gidjin requested changes
LGTM, just needs a couple of unit tests that I mentioned and then I'm happy to approve.

2023-02-09 19:12 UTC, gidjin commented on src/lists/Announcement.ts
> +              return DateTime.now().toJSDate()
Suggestion: add tests to test that a date can be set in the future properly and that if one is not set that a time in the near past is set for us. I believe I added examples in the Article tests but let me know if you need a hand with that.

2023-02-09 19:12 UTC, gidjin commented on src/lists/Announcement.ts
> +          validateInput: async ({
Suggestion: add tests for validation, confirm that a date in the past (beyond 4 hours) calls `addValidationError`, and only on update of publishedDate. I added a similar test for Article, but let me know if you need help with that.

2023-02-13 18:48 UTC, jbecker01 commented
@jcbcapps when setting a date and time and then saving, it's not updating the status to published. I have to go back and click on publish, which at that point sets the publish time and date to now.

2023-02-13 18:52 UTC, jcbcapps commented
> @jcbcapps when setting a date and time and then saving, it's not updating the status to published. I have to go back and click on publish, which at that point sets the publish time and date to now.

@jbecker01 Just pushed up some changes that should fix this!

2023-02-14 07:04 UTC, jbecker01 commented
:+1:

2023-02-14 23:08 UTC, gidjin approved these changes
LGTM!

2023-02-22 20:21 UTC, merged