feat: Add Bookmark, Collection schema
USSF-ORBIT/ussf-portal-cms pull request #30
Opened 2022-04-11 18:13 UTC by jcbcapps

# SC-192

## Proposed changes

- Adds Bookmark and Collection schemas
- Lowers required test coverage down to 50% for unit tests
---

## Reviewer notes

- Log into the portal as a user without CMS access (`user1 / user1pass`) and try to navigate to the CMS. You should not be able to access it.
- Log into the portal as a user with CMS access (`cmsuser / cmsuserpass`) and try to navigate to the CMS. You should be able to access it.
- While logged in as a user with CMS access, verify that you can create, read, and update Bookmarks and Collections.
- While logged in as a user with CMS access, verify that you cannot delete any Bookmarks or Collections.
## Setup

Testing this PR requires running both the CMS and portal app locally:

1. Make sure you have the portal repo checked out, and the environment variable set to its path (in the CMS repo):
`export PORTAL_PATH=../ussf-portal-client/`
2. Start the portal app and other services in docker:
`yarn portal:up`
3. Start the CMS app:
`yarn build && yarn start`
4. You should be able to access the CMS at http://localhost:3001/ and the portal at http://localhost:3000/
---

## Code review steps

### As the original developer, I have

- [ ] Met the acceptance criteria, or will meet them in subsequent PRs or stories
  - ... 
- [ ] Created new stories in Storybook if applicable
  - [ ] Checked that all Storybook accessibility checks are passing
- [ ] Created/modified automated unit tests in Jest
  - [ ] Including jest-axe checks when UI changes
- [ ] Created/modified automated E2E tests in Cypress
  - [ ] Including cypress-axe checks when UI changes
- Performed [a11y testing](https://github.com/trussworks/accessibility/blob/master/sample_a11y_testing_process.md):
  - [ ] Checked responsiveness in mobile, tablet, and desktop
  - [ ] Checked keyboard navigability
  - [ ] Tested with [VoiceOver](https://dequeuniversity.com/screenreaders/voiceover-keyboard-shortcuts) in Safari
  - [ ] Checked VO's [rotor menu](https://github.com/trussworks/accessibility/blob/master/README.md#how-to-use-the-rotor-menu) for landmarks, page heading structure and links
  - [ ] Used a browser a11y tool to check for issues (WAVE, axe, ANDI or Accessibility addon tab for Storybook)
- [ ] Requested a design review for user-facing changes
- For any new migrations/schema changes:
  - [ ] Followed guidelines for zero-downtime deploys

### As code reviewer(s), I have

- [ ] Pulled this branch locally and tested it
- [ ] Reviewed this code and left comments
- [ ] Checked that all code is adequately covered by tests
- [ ] Made it clear which comments need to be addressed before this work is merged
- [ ] Considered marking this as accepted even if there are small changes needed
- Performed [a11y testing](https://github.com/trussworks/accessibility/blob/master/sample_a11y_testing_process.md):
  - [ ] Checked responsiveness in mobile, tablet, and desktop
  - [ ] Checked keyboard navigability
  - [ ] Tested with [VoiceOver](https://dequeuniversity.com/screenreaders/voiceover-keyboard-shortcuts) in Safari
  - [ ] Checked VO's [rotor menu](https://github.com/trussworks/accessibility/blob/master/README.md#how-to-use-the-rotor-menu) for landmarks, page heading structure and links
  - [ ] Used a browser a11y tool to check for issues (WAVE, axe, ANDI or Accessibility addon tab for Storybook)

### As a designer reviewer, I have

- [ ] Checked in the design translated visually
- [ ] Checked behavior
- [ ] Checked different states (empty, one, some, error)
- [ ] Checked for landmarks, page heading structure, and links
- [ ] Tried to break the intended flow
- Performed [a11y testing](https://github.com/trussworks/accessibility/blob/master/sample_a11y_testing_process.md):
  - [ ] Checked responsiveness in mobile, tablet, and desktop
  - [ ] Checked keyboard navigability
  - [ ] Tested with [VoiceOver](https://dequeuniversity.com/screenreaders/voiceover-keyboard-shortcuts) in Safari
  - [ ] Checked VO's [rotor menu](https://github.com/trussworks/accessibility/blob/master/README.md#how-to-use-the-rotor-menu) for landmarks, page heading structure and links
  - [ ] Used a browser a11y tool to check for issues (WAVE, axe, ANDI or Accessibility addon tab for Storybook)

### As a test user, I have

- Run through the [Test Script](hhttps://docs.google.com/spreadsheets/d/1eV8UK0aJZ0qrzjnXf5SJ_uRiV7bpsj3yrhRFEkjOvV4/edit?usp=sharing):
  - [ ] On commercial internet in IE11
  - [ ] On commercial internet in Firefox
  - [ ] On commercial internet in Chrome
  - [ ] On commercial internet in Safari
  - [ ] On NIPR in IE11
  - [ ] On NIPR in Firefox
  - [ ] On NIPR in Chrome
  - [ ] On NIPR in Safari
  - [ ] On a mobile device in Firefox
  - [ ] On a mobile device in Chrome
  - [ ] On a mobile device in Safari
- [ ] Added any anomalous behavior to this PR

---

## Screenshots

2022-04-11 18:27 UTC, abbyoung commented on src/lists/Bookmark.ts
> +  fields: {
Should we add a `collections` field and relationship to Bookmarks, similar to the relationship on Collections? It would allow users to add a new bookmark to many collections when they create it. cc @suzubara

2022-04-11 18:54 UTC, jcbcapps commented on src/lists/Bookmark.ts
> +  fields: {
Looking at the Prisma schema, it generates a collections field for Bookmark based off the relationship on Collections. It seems that may be the same thing as what you're talking about? Not sure.

2022-04-11 19:43 UTC, suzubara commented on src/lists/Bookmark.ts
> +  fields: {
I think what @abbyoung is suggesting would show a field in the UI for Bookmarks so you can add related Collections when editing/creating a Bookmark. That seems like a good idea so I say go for it!

2022-04-11 19:50 UTC, suzubara reviewed
Reviewed the code & changes locally, the schema looks good to me! I would agree with adding the Collection relationship to the Bookmark schema so you can view/edit related Collections from the Bookmark UI

2022-04-11 23:01 UTC, abbyoung commented on src/lists/Collection.ts
> +    bookmarks: relationship({ ref: 'Bookmark', many: true }),
This shows the correct UI, but needs a small tweak for the relationship to work properly.

Right now, you can go to a Collection > add a bookmark to the bookmarks field. But when you navigate to the Bookmark's page, it won't show the collection in its collections field.

To have one update the other accordingly, try updating this to `ref: Bookmark.collections` here.

([source](https://keystonejs.com/docs/walkthroughs/lesson-2#connect-users-with-posts))

2022-04-11 23:02 UTC, abbyoung commented on src/lists/Bookmark.ts
> +    collections: relationship({ ref: 'Collection', many: true }),
This shows the correct UI, but needs a small tweak for the relationship to work properly.

Right now, you can go to a Bookmark > add a collection to the collections field. But when you navigate to the Collection's page, it won't show the bookmark in its bookmarks field.

To have one update the other accordingly, try updating this to `ref: Collection.bookmarks` here.

([source](https://keystonejs.com/docs/walkthroughs/lesson-2#connect-users-with-posts))

2022-04-11 23:05 UTC, abbyoung requested changes
UI looks good, and all the permissions work as expected! There's one small tweak needed for the collection + bookmark relationship, then it's good to go ⭐

2022-04-12 16:39 UTC, abbyoung approved these changes
🎉 ✅

2022-04-12 17:22 UTC, merged