feat: Schema for Article relationship fields (Byline, Location, Label, Tag)
USSF-ORBIT/ussf-portal-cms pull request #48
Opened 2022-05-16 22:07 UTC by jcbcapps

# SC-510

## Proposed changes

Adds schema for the following items, and adds each item to the [Article schema](https://github.com/USSF-ORBIT/ussf-portal-cms/pull/44):

- Byline
- Label
- Location
- Tag

---

## Reviewer notes

Log in as each user type to adequately test permissions:

- Log in as `cmsadmin:cmsadminpass` and:
  - Verify that you can create/read/update/delete Bylines, Labels, Locations and Tags as `cmsadmin` as well as read/update/delete any Bylines, Labels, Locations and Tags created by other users
- Log in as `cmsauthor:cmsauthorpass` and:
  - Verify that you can read all Bylines, Labels, Locations and Tags
  - Verify that you can create/read/update/delete Tags as `cmsauthor` but _cannot_ update/delete Tags created by other users
- Log in as `cmsmanager:cmsmanagerpass` and:
  - Verify that you can read _all_ Bylines, Labels, Locations and Tags
  - Verify that you can create/read/update/delete Tags as `cmsmanager` as well as read/update/delete Tags created by other users
- Log in as `cmsuser:cmsuserpass` and:
  - Verify that you _cannot_ create or read/update/delete any Bylines, Labels, Locations or Tags

## Setup

You will need to test on your local environment in order to log in as different test users. Make sure you are running the portal client & required services (ie., yarn portal:up in the CMS repo).

The first time you log in as each user, you will need to also log in as the `cmsadmin` and assign each user its role. For example:

- Log in as `cmsauthor / cmsauthorpass` to create the user in keystone. Role will default to User
- Log in as `cmsadmin` (it's convenient to just stay logged in as the admin in an incognito window) and assign the Author role to `cmsauthor`
Now when you refresh the page as `cmsauthor` you should have the correct role & permissions.
---

## Code review steps

### As the original developer, I have

- [ ] Met the acceptance criteria, or will meet them in subsequent PRs or stories
- [ ] Created/modified automated unit tests in Jest
- [ ] Created/modified automated E2E tests in Playwright

### As code reviewer(s), I have

- [ ] Pulled this branch locally and tested it
- [ ] Reviewed this code and left comments
- [ ] Checked that all code is adequately covered by tests
- [ ] Made it clear which comments need to be addressed before this work is merged
- [ ] Considered marking this as accepted even if there are small changes needed

2022-05-24 23:51 UTC, jbecker01 commented
I'm not sure if this is by design, but for authors, they do not see the updated/created by fields populated when tags, labels, or bylines are created. 

![Screen Shot 2022-05-24 at 4 50 19 PM](https://user-images.githubusercontent.com/52676444/170150129-30ff3c76-7be7-436c-bd93-d27eaadbf066.png)

2022-05-24 23:53 UTC, jbecker01 commented
Would it be possible to hide the create buttons for authors? They can click on the button to add a new byline, location, label, and tag which opens up a prompt that lets them enter in a value however at that point we deny them due to permissions. It would be nice to not even expose that option if they are unable to use it. 
![Screen Shot 2022-05-24 at 4 51 29 PM](https://user-images.githubusercontent.com/52676444/170150372-7e5da1ae-990d-4bc8-ab4a-f1d5118959d3.png)

2022-05-25 19:26 UTC, suzubara commented
> Would it be possible to hide the create buttons for authors? They can click on the button to add a new byline, location, and label which opens up a prompt that lets them enter in a value however at that point we deny them due to permissions. It would be nice to not even expose that option if they are unable to use it.

➕  I think you can use the `ui.hideCreate` [option](https://keystonejs.com/docs/apis/fields#relationship-type) to remove these from the UI. The only field that anyone should be able to create in-line is `tag`

2022-05-25 19:49 UTC, suzubara requested changes
My main feedback is what we discussed about re-generating the migrations and giving them names! let me know if you would like to pair at all on that. Otherwise the schema code & tests look great!

2022-05-25 19:49 UTC, suzubara commented on src/lists/Article.ts
> +      tag: relationship({ ref: 'Tag', many: true }),
additionally, since they are "many" of these on an Article, can we change the field names to be plural for `labels` & `tags`?

2022-05-27 15:31 UTC, suzubara approved these changes
Thanks for making those changes, this looks good to me!

2022-05-27 16:25 UTC, merged